# Docker Compose configuration for WildSight.
# This file will evolve as services are introduced throughout development.

services:
  backend:
    build:
      context: ./backend
      dockerfile: DockerFile
    container_name: wildsight-backend

    env_file:
      - .env

    ports:
      - "8000:8000"
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
      dockerfile: DockerFile
    container_name: wildsight-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  database:
    image: postgis/postgis:17-3.5
    container_name: wildsight-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
    - "5432:5432"
    # Make sure database does not disappear when container is restarted. 
    # This is where the database will be stored.
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d

volumes: 
  postgres_data: