"""add taxonomy and observation models

Revision ID: 87a6e742906c
Revises: c8f000700750
Create Date: 2026-07-03 14:49:00.194558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = '87a6e742906c'
down_revision: Union[str, Sequence[str], None] = 'c8f000700750'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('state_province', sa.String(length=100), nullable=False),
    sa.Column('municipality', sa.String(length=100), nullable=False),
    sa.Column('locality', sa.String(length=255), nullable=False),
    sa.Column('coordinates', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_name'), 'locations', ['name'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('taxon_order', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_name'), 'orders', ['name'], unique=True)
    op.create_table('families',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('family_code', sa.String(length=50), nullable=False),
    sa.Column('common_name', sa.String(length=100), nullable=False),
    sa.Column('scientific_name', sa.String(length=100), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete="CASCADE",),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_families_family_code'), 'families', ['family_code'], unique=True)
    op.create_table('species',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ebird_code', sa.String(length=20), nullable=False),
    sa.Column('common_name', sa.String(length=255), nullable=False),
    sa.Column('scientific_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('wildlife_group', sa.String(length=50), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete="CASCADE",),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_species_common_name'), 'species', ['common_name'], unique=False)
    op.create_index(op.f('ix_species_ebird_code'), 'species', ['ebird_code'], unique=True)
    op.create_index(op.f('ix_species_family_id'), 'species', ['family_id'], unique=False)
    op.create_index(op.f('ix_species_scientific_name'), 'species', ['scientific_name'], unique=False)
    op.create_table('observations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('species_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('observation_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_observations_location_id'), 'observations', ['location_id'], unique=False)
    op.create_index(op.f('ix_observations_observation_datetime'), 'observations', ['observation_datetime'], unique=False)
    op.create_index(op.f('ix_observations_species_id'), 'observations', ['species_id'], unique=False)
    op.create_index(op.f('ix_observations_user_id'), 'observations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_observations_user_id'), table_name='observations')
    op.drop_index(op.f('ix_observations_species_id'), table_name='observations')
    op.drop_index(op.f('ix_observations_observation_datetime'), table_name='observations')
    op.drop_index(op.f('ix_observations_location_id'), table_name='observations')
    op.drop_table('observations')
    op.drop_index(op.f('ix_species_scientific_name'), table_name='species')
    op.drop_index(op.f('ix_species_family_id'), table_name='species')
    op.drop_index(op.f('ix_species_ebird_code'), table_name='species')
    op.drop_index(op.f('ix_species_common_name'), table_name='species')
    op.drop_table('species')
    op.drop_index(op.f('ix_families_family_code'), table_name='families')
    op.drop_table('families')
    op.drop_index(op.f('ix_orders_name'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_locations_name'), table_name='locations')
    op.drop_table('locations')
    # ### end Alembic commands ###
