"""add locations table

Revision ID: 33aa622041a6
Revises: 87a6e742906c
Create Date: 2026-07-04 12:48:52.102773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33aa622041a6'
down_revision: Union[str, Sequence[str], None] = '87a6e742906c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('families_order_id_fkey'), 'families', type_='foreignkey')
    op.create_foreign_key(None, 'families', 'orders', ['order_id'], ['id'])
    op.add_column('locations', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('locations', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('locations', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('locations', 'country',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('locations', 'state_province',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('locations', 'municipality',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('locations', 'locality',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('observations', 'location_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('species_family_id_fkey'), 'species', type_='foreignkey')
    op.create_foreign_key(None, 'species', 'families', ['family_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'species', type_='foreignkey')
    op.create_foreign_key(op.f('species_family_id_fkey'), 'species', 'families', ['family_id'], ['id'], ondelete='CASCADE')
    op.alter_column('observations', 'location_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('locations', 'locality',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('locations', 'municipality',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('locations', 'state_province',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('locations', 'country',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('locations', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('locations', 'updated_at')
    op.drop_column('locations', 'created_at')
    op.drop_constraint(None, 'families', type_='foreignkey')
    op.create_foreign_key(op.f('families_order_id_fkey'), 'families', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
