"""add species display groups

Revision ID: 471d94ffbbea
Revises: c773274f55fa
Create Date: 2026-07-08 17:34:36.479734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '471d94ffbbea'
down_revision: Union[str, Sequence[str], None] = 'c773274f55fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('species_display_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('wildlife_group', sa.String(length=50), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_species_display_groups_name'), 'species_display_groups', ['name'], unique=True)
    op.create_index(op.f('ix_species_display_groups_wildlife_group'), 'species_display_groups', ['wildlife_group'], unique=False)
    op.create_table('species_display_group_members',
    sa.Column('species_id', sa.UUID(), nullable=False),
    sa.Column('display_group_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['display_group_id'], ['species_display_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('species_id', 'display_group_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('species_display_group_members')
    op.drop_index(op.f('ix_species_display_groups_wildlife_group'), table_name='species_display_groups')
    op.drop_index(op.f('ix_species_display_groups_name'), table_name='species_display_groups')
    op.drop_table('species_display_groups')
    # ### end Alembic commands ###
