"""remove species display group members

Revision ID: 52c527188913
Revises: 2a48d9307d8c
Create Date: 2026-07-08 17:46:54.747166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52c527188913'
down_revision: Union[str, Sequence[str], None] = '2a48d9307d8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('species_display_group_members')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('species_display_group_members',
    sa.Column('species_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('display_group_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['display_group_id'], ['species_display_groups.id'], name=op.f('species_display_group_members_display_group_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], name=op.f('species_display_group_members_species_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('species_id', 'display_group_id', name=op.f('species_display_group_members_pkey'))
    )
    # ### end Alembic commands ###
