"""add ebird id to hotspots

Revision ID: 62e388e58634
Revises: 6992e2451a24
Create Date: 2026-07-07 14:56:59.170185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62e388e58634'
down_revision: Union[str, Sequence[str], None] = '6992e2451a24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotspots', sa.Column('ebird_id', sa.String(length=20), nullable=False))
    op.alter_column('hotspots', 'source',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.create_index(op.f('ix_hotspots_ebird_id'), 'hotspots', ['ebird_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hotspots_ebird_id'), table_name='hotspots')
    op.alter_column('hotspots', 'source',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('hotspots', 'ebird_id')
    # ### end Alembic commands ###
