"""add hotspot distance

Revision ID: 65287b3c9c8f
Revises: 62e388e58634
Create Date: 2026-07-07 15:06:27.119214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65287b3c9c8f'
down_revision: Union[str, Sequence[str], None] = '62e388e58634'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('observations', sa.Column('distance_to_hotspot_m', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('observations', 'distance_to_hotspot_m')
    # ### end Alembic commands ###
