"""add astronomy and hotspot relationships

Revision ID: 6992e2451a24
Revises: 5cb740c48b7e
Create Date: 2026-07-07 13:07:04.191493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = '6992e2451a24'
down_revision: Union[str, Sequence[str], None] = '5cb740c48b7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('astronomy',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sunrise', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sunset', sa.DateTime(timezone=True), nullable=True),
    sa.Column('day_length', sa.Float(), nullable=True),
    sa.Column('season', sa.String(length=20), nullable=True),
    sa.Column('moon_phase', sa.String(length=30), nullable=True),
    sa.Column('moon_illumination', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hotspots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('coordinates', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hotspots_name'), 'hotspots', ['name'], unique=False)
    op.add_column('observations', sa.Column('astronomy_id', sa.UUID(), nullable=True))
    op.add_column('observations', sa.Column('hotspot_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'observations', 'hotspots', ['hotspot_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'observations', 'astronomy', ['astronomy_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'observations', type_='foreignkey')
    op.drop_constraint(None, 'observations', type_='foreignkey')
    op.drop_column('observations', 'hotspot_id')
    op.drop_column('observations', 'astronomy_id')
    op.drop_index(op.f('ix_hotspots_name'), table_name='hotspots')
    op.drop_table('hotspots')
    op.drop_table('astronomy')
    # ### end Alembic commands ###
