"""add countries and species countries

Revision ID: 946b593a3cf8
Revises: 33aa622041a6
Create Date: 2026-07-06 15:36:44.414518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '946b593a3cf8'
down_revision: Union[str, Sequence[str], None] = '33aa622041a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('iso_code', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iso_code')
    )
    op.create_table('species_countries',
    sa.Column('species_id', sa.UUID(), nullable=False),
    sa.Column('country_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ),
    sa.PrimaryKeyConstraint('species_id', 'country_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('species_countries')
    op.drop_table('countries')
    # ### end Alembic commands ###
