"""add inaturalist image fields

Revision ID: c773274f55fa
Revises: 65287b3c9c8f
Create Date: 2026-07-08 12:22:41.725589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c773274f55fa'
down_revision: Union[str, Sequence[str], None] = '65287b3c9c8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('species', sa.Column('inat_taxon_id', sa.Integer(), nullable=True))
    op.add_column('species', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.add_column('species', sa.Column('thumbnail_url', sa.String(length=500), nullable=True))
    op.add_column('species', sa.Column('image_license', sa.String(length=100), nullable=True))
    op.add_column('species', sa.Column('image_attribution', sa.String(length=500), nullable=True))
    op.add_column('species', sa.Column('image_source', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_species_inat_taxon_id'), 'species', ['inat_taxon_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_species_inat_taxon_id'), table_name='species')
    op.drop_column('species', 'image_source')
    op.drop_column('species', 'image_attribution')
    op.drop_column('species', 'image_license')
    op.drop_column('species', 'thumbnail_url')
    op.drop_column('species', 'image_url')
    op.drop_column('species', 'inat_taxon_id')
    # ### end Alembic commands ###
