"""add weather model and observation enrichment

Revision ID: fd4dc1e56da8
Revises: 946b593a3cf8
Create Date: 2026-07-07 08:20:47.220914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd4dc1e56da8'
down_revision: Union[str, Sequence[str], None] = '946b593a3cf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('observation_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('apparent_temperature', sa.Float(), nullable=True),
    sa.Column('relative_humidity', sa.Float(), nullable=True),
    sa.Column('dew_point', sa.Float(), nullable=True),
    sa.Column('pressure', sa.Float(), nullable=True),
    sa.Column('cloud_cover', sa.Float(), nullable=True),
    sa.Column('visibility', sa.Float(), nullable=True),
    sa.Column('uv_index', sa.Float(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('wind_direction', sa.Float(), nullable=True),
    sa.Column('wind_gust', sa.Float(), nullable=True),
    sa.Column('precipitation', sa.Float(), nullable=True),
    sa.Column('weather_code', sa.Integer(), nullable=True),
    sa.Column('weather_description', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_observation_datetime'), 'weather', ['observation_datetime'], unique=False)
    op.add_column('locations', sa.Column('elevation', sa.Float(), nullable=True))
    op.add_column('locations', sa.Column('biome', sa.String(length=100), nullable=True))
    op.add_column('locations', sa.Column('habitat', sa.String(length=100), nullable=True))
    op.add_column('locations', sa.Column('protected_area', sa.String(length=255), nullable=True))
    op.add_column('observations', sa.Column('weather_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'observations', 'weather', ['weather_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'observations', type_='foreignkey')
    op.drop_column('observations', 'weather_id')
    op.drop_column('locations', 'protected_area')
    op.drop_column('locations', 'habitat')
    op.drop_column('locations', 'biome')
    op.drop_column('locations', 'elevation')
    op.drop_index(op.f('ix_weather_observation_datetime'), table_name='weather')
    op.drop_table('weather')
    # ### end Alembic commands ###
